openapi: 3.0.4
info:
  title: database API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9

servers:
  - url: http://localhost:3000
    description: Optional server description, e.g. Main (production) server
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing

paths:
  /data:
    get:
      summary: Returns a list of stock data.
      description: Optional extended description in CommonMark or HTML.
      responses:
        "200": # status code
          description: A JSON array of stock data
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
    post:
      summary: Creates a new stock data entry.
      description: Optional extended description in CommonMark or HTML.
      requestBody:
        description: Stock data to add
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                name:
                  type: string
                price:
                  type: number
      responses:
        "201": # status code
          description: Stock data created successfully